### ISSUE TITLE
用Nano-58M-20241018直接推理，乱码无法复现readme动图

### ISSUE THREAD

**Issue by yxnchen** [bd4sur/Nano#2]
使用步骤1、4，下载了HF的`nano_58m_20241018_188000.pt`，直接推理，输出如下，请问正常吗
![image](https://github.com/user-attachments/assets/69771d17-d1ca-472a-81ce-e62831639489)

**Comment by bd4sur** [comment]
你好：

这个模型是使用GPT结构训练的（没有GQA、FFN层使用GELU激活函数），而现在主分支上最新的实现已经替换成Llama结构（GQA、SwiGLU）。模型结构与当前最新实现不符合。

如果希望测试 Nano-58M-20241018 这个模型，请使用10月18日前后的提交，例如 https://github.com/bd4sur/Nano/commit/161b3d89ae836cae8a4ff1735fd824ab3ec26ab9 。

采用Llama结构的新模型正在训练（基于10B词元的语料），近期将放出。后续将不再变更模型结构（毕竟训练太贵了233）
