### ISSUE TITLE
也许移除 infer.py 中的 `import readline` 会好一点？| Maybe removing the `import readline` in infer.py would be better?

### ISSUE THREAD

**Issue by thefatwhale** [bd4sur/Nano#3]
在推理代码 `infer.py` 中导入了 readline 模块，该模块在文件中并未使用。
不知道为什么存在在这里。希望可以移除掉该行。

位置： `/infer.py:3`

该模块并未存在在 requirements.txt 文件中，同时也不是依赖项的依赖。
正常执行推理会导致 python 报错缺少模块 readline
Windows 用户在尝试安装该包时，会出现错误，因为该模块不支持 Windows 系统。

因此该模块在此处并没有作用，希望移除掉该行。谢谢。

---

The readline module is imported in the inference code `infer.py`, which is not used in the file.
I don't know why it is there. I hope it is possible to remove the line.

position： `/infer.py:3`

This module does not exist in the requirements.txt file and is not a dependency of the dependencies.
Normal reasoning will cause python to report that the module readline is missing.
Windows users will get an error when trying to install the package because the module is not supported on Windows systems.

So the module has no role here and I would like to remove the line. Thank you.

**Comment by bd4sur** [comment]
① 该模块的功能和用法请参考：https://docs.python.org/3/library/readline.html#module-readline

② Windows下无法使用该模块，您可以自行去掉。

**Comment by thefatwhale** [comment]
感谢，我已经学习并了解了 readline 在此处的作用。

_readline 模块可以在仅仅导入之后就为终端输入提供 类emacs 快捷键操作。_

**但我仍然希望增加额外代码，而不是克隆后用户手动删除该行代码的导入**
来增加代码在不同平台的健壮性

此模块在：windows android ios webasm 等平台不可用

![image](https://github.com/user-attachments/assets/042cfbbf-f3a5-40f6-ab21-b180be200b35)

**建议添加类似代码，保证在不同平台正常运行，感谢！**

```python
try:
    import readline
except:
    pass
```
