### ISSUE TITLE
`deepspeed` 在 Windows 系统上安装失败 | Installation of `deepspeed` fails on Windows systems

### ISSUE THREAD

**Issue by thefatwhale** [bd4sur/Nano#4]
**deepspeed 在 Windows 系统上安装失败**

如果可以的话，修改 `requirements.txt` 中的 deepspeed版本
`deepspeed==0.15.0`
此版本经过测试可以正常安装。
_0.15.4 同样安装失败。_

如果不可以修改 `requirements.txt` 中 deepspeed 依赖的版本，建议在 README.md 中标注一下。

以求避免 Windows 用户安装失败。谢谢。

---

**deepspeed failed to install on Windows system**

If possible, change the version of deepspeed in `requirements.txt` to
`deepspeed==0.15.0`
This version has been tested and installed correctly.
_0.15.4 also fails. _

If it is not possible to change the version of the deepspeed dependency in `requirements.txt`, it is recommended to mark it in README.md.

To avoid installation failure for Windows users. Thank you.

**Comment by bd4sur** [comment]
感谢指出。

Nano对DeepSpeed的支持是尝试性的、临时性的，后续可能会彻底去掉有关DeepSpeed的内容。故不打算在readme中作进一步的说明。

**Comment by thefatwhale** [comment]
好的，感谢您的回复。
我会将解决方法贴在这里方便遇到问题的用户搜索。

```
pip3 install deepspeed==0.15.0
```

https://github.com/microsoft/DeepSpeed/issues/6702#issuecomment-2455149777

---

关键字： aio.lib deepspeed deepspeed==0.14.2 LINK : fatal error LNK1181: cannot open input file 'aio.lib'
